{% set name = "mdf_toolbox" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 800525741361b348538bed27af22d5db97deb39b72e27173e7c420a3eec31b6a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pip
    - globus-nexus-client >=0.2.8
    - globus-sdk >=1.7.0
    - requests >=2.18.4
    - fair-research-login

test:
  imports:
    - mdf_toolbox
  commands:
    - pip check

about:
  home: https://github.com/materials-data-facility/toolbox
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Toolbox is a collection of the Materials Data Facility tools and utilities.

  description: |
    Toolbox is a collection of the Materials Data Facility tools and utilities.
  doc_url: https://github.com/materials-data-facility/toolbox
  dev_url: https://github.com/materials-data-facility/toolbox

extra:
  recipe-maintainers:
    - jan-janssen
