{% set name = "mdf_toolbox" %}
{% set version = "0.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materials-data-facility/toolbox/archive/{{ version }}.tar.gz
  sha256: 017ff4b91abdf4e8cdd9fb2d0022870e0349647364a87810fbc2fc358dd27283

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - globus-nexus-client >=0.2.8
    - globus-sdk >=1.7.0
    - requests >=2.18.4
    - fair-research-login
    - jsonschema

test:
  imports:
    - mdf_toolbox
  commands:
    - pip check

about:
  home: https://github.com/materials-data-facility/toolbox
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Toolbox is a collection of the Materials Data Facility tools and utilities.

  description: |
    Toolbox is a collection of the Materials Data Facility tools and utilities.
  doc_url: https://github.com/materials-data-facility/toolbox
  dev_url: https://github.com/materials-data-facility/toolbox

extra:
  recipe-maintainers:
    - jan-janssen
